const { successResponse } = require('../utils/globalSuccessResponse');
const AppError = require('../utils/errorResponse');



exports.createReview = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}
exports.getReview = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}
exports.getAllReview = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}
exports.deleteReview = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}

