const { successResponse } = require('../utils/globalSuccessResponse');
const AppError = require('../utils/errorResponse');



exports.updatePassword = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}
exports.updateDetails = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}
exports.getDetails = async (req, res, next) =>{
    try {
        
    } catch (error) {
        return res.status(400).json({
            status: 'fail',
            err: error
        });
    }
}


